// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "9a7a8b50bcf6739e5a1caa39a10d092d"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"92a78a558d554c3ef4f2ee69a0c73459": "1f8b08000000000000ffaae6525050cacc2b2e49ccc951b25200711514944a2a0b5295ac1494f293b252934b947420a20545f905a9452599a9c52095b550d1c49494cc92ccfcbcc49c0064f992a2d2542e05855aae5a2e40000000ffffb75adda464000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("schema", "./schema")
		b.SetResolver("mixin.json", packr.Pointer{ForwardBox: gk, ForwardPath: "92a78a558d554c3ef4f2ee69a0c73459"})
	}()

	return nil
}()
